String setLanguage = 'en';
final Map<String, Map<String, String>> captions = {
  'en': {
    'login': 'Login',
    'signin': 'Sign in',
    'signup': 'Sign up',
    'addabanner!': 'Add a banner!',
    'password': 'Password',
    'emailhere': 'Email here!',
    'passwordhere': 'Password here!',
    'forgotpassword?': "Forgot Password?",
    'sociallogin': 'Social login', //google and facebook login
    'newuser?': 'New user?',
    'signup!': 'Sign up!',
    'youareorganization?': 'You are organization?',
    'clickhere': 'Click here!',
    'whatareyourinterstedtags?': 'What are your interested tags?',
    'home': 'Home',
    'organizations': 'Organizations',
    'logout': 'Log out',
    'map': 'Map',
    'donate': 'Donate',
    'donate!': 'Donate!',
    'message': 'Message',
    'editprofile': 'Edit profile',
    'organization': 'Organization',
    'chat': 'chat',
    'removeimage': 'Remove image',
    'viewpost': 'View Post',
    'writeacomment': 'Write a comment',
    'writeacomment...': 'Write a comment...',
    'create!': 'Create!',
    'createcampaign': 'Create campaign',
    'create': 'Create',
    'save': 'Save',
    'nickname': 'Nickname',
    'bio': 'Bio',
    'namehere!': 'Name here!',
    'nicknamehere!': 'Nickname here!',
    'biohere!': 'Bio here!',
    'createpost': 'Create post',
    'whatsonyourmind': "What's on your mind",
    'campaign': 'Campaign',
    'yesterday': 'Yesterday',
    'hour': 'Hour',
    'hours': 'Hours',
    'min': 'Min',
    'mins': 'Mins',
    'item': 'Item',
    'campaign': 'Campagin',
    'event': 'Event',
    'pickaplace': 'Pick a place',
    'getyourlocation': 'Get your location',
    'address': 'Address',
    'title': 'Title',
    'or': 'Or',
    'titlehere...': 'Title here...',
    'now': 'Now',
    'information': 'Information',
    'describe': "Describe",
    'describehere': 'Describe here...',
    'exp': 'Exp',
    'non-exp': 'Non-expring(tap to select a day)',
    'youraddresswillshowuphere!': 'Your address will show up here!',
    'submit': 'Submit',
    'following': 'Following',
    'yours': 'Yours',
    'editprofile': 'Edit profile',
    'send': 'Send',
    'selectaday': 'Select a day',
    'second': 'Second',
    'seconds': 'Seconds',
    'introduceyourcampaign': 'Introduce your campaign...',
    'detail': 'Detail',
    'tellmore': 'Tell more',
    'from': 'From',
    'to': 'To',
    'until': 'Until',
    'picktags': 'Pick tags',
    'needvolunteers': 'Need volunteers',
    'needdonors': 'Need donors',
    'owner': 'Owner',
    'type': 'Type',
    'enteryouraddress': "Enter your address",
    "telleveryoneaboutyourorganization.":
        "Tell everyone about your organization.",
    'contact': "Contact",
    'joinus!': 'Join us!', "done": "Done",
    'introduceyourself': 'Introduce yourself',
    'writesomethinghere...': 'Write something here...', 'followed': 'Followed',
    'follow!': "Follow!",
    'profile': 'Profile',
    'day': 'Day',
    'days': 'Days',
    'organizers': 'Organizers',
    'need': "Need",
    'introduction': 'Introduction',
    'comment': "Comment",
    'setting': "Setting",
    'language': "Language",
    'english': "English",
    'vietnamese': "Vietnamese"
  },
  'vi': {
    'login': 'Đăng nhập',
    'signin': 'Đăng nhập',
    'signup': 'Đăng kí',
    'addabanner!': 'Tải lên ảnh biểu ngữ!',
    'password': 'Mật khẩu',
    'emailhere': 'Nhập email...',
    'passwordhere': 'Nhập mật khẩu...',
    'forgotpassword?': "Quên mật khẩu?",
    'sociallogin': 'Đăng nhập với', //google and facebook login
    'newuser?': 'Người dùng mới?',
    'signup!': 'Đăng nhập!',
    'youareorganization?': 'Bạn là từ một tổ chức?',
    'clickhere': 'Bấm vào đây!',
    'whatareyourinterstedtags?': 'Những từ khóa nào mà bạn đang quan tâm?',
    'home': 'Trang chủ',
    'organizations': 'Tổ chức',
    'logout': 'Thoát',
    'map': 'Bản đồ',
    'donate': 'Quyên góp',
    'donate!': 'Quyên góp!',
    'message': 'Trò chuyện',
    'editprofile': 'Chỉnh sửa',
    'organization': 'Tổ chức',
    'chat': 'Trò chuyện',
    'removeimage': 'Xóa ảnh',
    'viewpost': 'Bài viết',
    'writeacomment': 'Viết bình luận',
    'writeacomment...': 'Viết gì đó...',
    'create!': 'Bắt đầu chiến dịch!',
    'createcampaign': 'Bắt đầu chiến dịch',
    'create': 'Tạo',
    'save': 'Lưu lại',
    'nickname': 'Biệt danh',
    'bio': 'Giới thiệu bản thân',
    'namehere!': 'Tên của bạn?!',
    'nicknamehere!': 'Biệt danh của bạn?',
    'biohere!': 'Giới thiệu đôi chút về bản thân nào!',
    'createpost': 'Tạo bài viết',
    'whatsonyourmind': "Bạn đang nghĩ gì?",
    'campaign': 'Chiến dịch',
    'yesterday': 'Hôm qua',
    'hour': 'Giờ',
    'hours': 'Giờ',
    'min': 'Phút',
    'mins': 'Phút',
    'item': 'Đồ cho đi',
    'campaign': 'Chiến dịch',
    'event': 'Sự kiện',
    'pickaplace': 'Chọn 1 địa chỉ',
    'getyourlocation': 'Địa chỉ hiện tại',
    'address': 'Địa chỉ',
    'title': 'Tiêu đề',
    'or': 'Hoặc',
    'titlehere...': 'Đặt một tiêu đề',
    'now': 'Ngay lúc này',
    'information': 'Thông tin',
    'describe': "Mô tả",
    'describehere': 'Viết mô tả...',
    'exp': 'Hạn dùng',
    'non-exp': 'Không có hạn dùng(bấm vào để chọn HSD)',
    'youraddresswillshowuphere!': 'Địa chỉ của bạn sẽ hiển thị ở đây!',
    'submit': 'Tải lên',
    'following': 'Đang theo dõi',
    'yours': 'Tổ chức của bạn',
    'editprofile': 'Chỉnh sửa',
    'send': 'Gửi',
    'selectaday': 'Chọn một ngày',
    'second': 'Giây',
    'seconds': 'Giây',
    'introduceyourcampaign': 'Giới thiệu về chiến dịch của bạn',
    'detail': 'Chi tiết',
    'tellmore': 'Trình bày chi tiết...',
    'from': 'Từ',
    'to': 'đến',
    'until': 'Cho tới',
    'picktags': 'Chọn từ khóa',
    'needvolunteers': 'Cần tình nguyện viên',
    'needdonors': 'Cần quyên góp',
    'owner': 'Người sở hữu',
    'type': 'Loại',
    'enteryouraddress': "Nhập địa chỉ của bạn",
    "telleveryoneaboutyourorganization.":
        "Hãy cho mọi người biết về tổ chức của bạn!",
    'contact': "Liên hệ",
    'joinus!': 'Tham gia!', "done": "Gửi",
    'introduceyourself': 'Giới thiệu bản thân',
    'writesomethinghere...': 'Viết gì đó về bạn...', 'followed': 'Đã theo dõi',
    'follow!': "Theo dõi!",
    'profile': 'Trang cá nhân',
    'day': 'Ngày',
    'days': 'Ngày',
    'organizers': 'Tổ chức bởi',
    'need': "Đang cần",
    'introduction': 'Giới thiệu',
    'comment': "Bình luận",
    'setting': "Cài đặt",
    'language': "Ngôn ngữ",
    'english': "Tiếng Anh",
    'vietnamese': "Tiếng Việt"
  },
};
